name: Code Structure Verification

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  verify-structure:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']  # Single version for demonstration

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install core dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy pandas scikit-learn
    
    - name: Verify repository structure
      run: |
        python simple_test.py
    
    - name: Test V2 imports (no API dependencies)
      run: |
        python -c "
        import sys, os
        sys.path.append('v2-volatility-forecasting/src')
        # Test basic structure exists
        assert os.path.exists('v2-volatility-forecasting/src/config.py')
        assert os.path.exists('v2-volatility-forecasting/README.md')
        assert os.path.exists('LICENSE')
        print('✅ Repository structure verified')
        "